# Generated by Django 3.2.4 on 2021-06-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_prod_slide',
            field=models.BooleanField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='new_prod_slidea',
            field=models.BooleanField(blank=True, default=1),
        ),
    ]
