# Generated by Django 3.2.4 on 2021-06-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='date',
            new_name='date_of_birth',
        ),
    ]
